version: "3"
services:
  glpi:
    image: enzoakira/glpi:9.4.3
    container_name: glpi_web
    networks:
      - webglpi
    ports:
      - "410:80"
  mariadb:
    image: mariadb
    container_name: glpi_db
    hostname: mariadb
    networks:
      - webglpi
    volumes:
      - "db_glpi:/var/lib/mysql/db_glpi"
    environment:
      - MYSQL_ROOT_PASSWORD=SOMEPASS
      - MYSQL_DATABASE=glpi_db
      - MYSQL_USER=glpi
      - MYSQL_PASSWORD=SOMEPASS

networks:
  webglpi:

volumes:
  db_glpi: